import { TClient } from "@/types/models/client";
import { TChatwootConversation } from "@/types/models/chatwoot/conversation";

// Helper function to convert ISO date string to timestamp (milliseconds)
const dateToTimestamp = (dateString: string): number => {
  return new Date(dateString).getTime();
};

export const AGENTS: TClient[] = [
  {
    _id: "agent_analytics_001",
    contact_id: 2001,
    platform_id: "em_agent_analytics_001",
    name: "Analytics Agent",
    thumbnail:
      "https://api.dicebear.com/7.x/bottts/svg?seed=analytics&backgroundColor=4f46e5",
    email: "analytics@linkaiil.ai",
    phone: "+1-555-AI-0001",
    channel: "email",
    user: "user_agent_analytics_001",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-28T10:15:00.000Z",
  },
  {
    _id: "agent_inventory_002",
    contact_id: 2002,
    platform_id: "sms_agent_inventory_002",
    name: "Inventory Management Agent",
    thumbnail:
      "https://api.dicebear.com/7.x/bottts/svg?seed=inventory&backgroundColor=10b981",
    email: "inventory@linkaiil.ai",
    phone: "+1-555-AI-0002",
    channel: "sms",
    user: "user_agent_inventory_002",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-28T10:40:00.000Z",
  },
];

// export const CLIENTS: TChatwootConversation[] = [
//   {
//     id: 1001,
//     account_id: 1,
//     inbox_id: 1,
//     status: "open",
//     timestamp: dateToTimestamp("2025-12-01T14:30:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-01T14:30:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-01T14:30:00.000Z"),
//     unread_count: 1,
//     additional_attributes: {
//       chat_id: 1001,
//       business_connection_id: null,
//     },
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_1g2h3j4k5l6m7n8o9p0q",
//     messages: [
//       {
//         id: 1,
//         content: "Hello! I need help with my order",
//         account_id: 1,
//         inbox_id: 1,
//         conversation_id: 1001,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//         updated_at: "2025-12-01T14:25:00.000Z",
//         private: false,
//         status: "delivered",
//         source_id: "wa_1g2h3j4k5l6m7n8o9p0q",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1001,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Hello! I need help with my order",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 1,
//           last_activity_at: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//           contact_inbox: {
//             source_id: "wa_1g2h3j4k5l6m7n8o9p0q",
//           },
//         },
//         sender: {
//           id: 1001,
//           name: "Anya Smith",
//           available_name: "Anya Smith",
//           avatar_url: "https://i.pravatar.cc/150?img=1",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=1",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1001,
//         name: "Anya Smith",
//         email: "anya.smith@example.com",
//         phone_number: "+1-555-0101",
//         thumbnail: "https://i.pravatar.cc/150?img=1",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-11-10T10:00:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//       },
//       channel: "whatsapp",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-11-10T10:00:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-01T14:30:00.000Z"),
//     first_reply_created_at: null,
//     last_non_activity_message: {
//       id: 1,
//       content: "Hello! I need help with my order",
//       account_id: 1,
//       inbox_id: 1,
//       conversation_id: 1001,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//       updated_at: "2025-12-01T14:25:00.000Z",
//       private: false,
//       status: "delivered",
//       source_id: "wa_1g2h3j4k5l6m7n8o9p0q",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1001,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Hello! I need help with my order",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 1,
//         last_activity_at: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//         contact_inbox: {
//           source_id: "wa_1g2h3j4k5l6m7n8o9p0q",
//         },
//       },
//       sender: {
//         id: 1001,
//         name: "Anya Smith",
//         available_name: "Anya Smith",
//         avatar_url: "https://i.pravatar.cc/150?img=1",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=1",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-01T14:25:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1002,
//     account_id: 1,
//     inbox_id: 2,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-07T11:05:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-07T11:05:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-07T11:05:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_2r3s4t5u6v7w8x9y0z1a",
//     messages: [
//       {
//         id: 2,
//         content: "Thanks for the quick response!",
//         account_id: 1,
//         inbox_id: 2,
//         conversation_id: 1002,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//         updated_at: "2025-12-07T11:00:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "ig_2r3s4t5u6v7w8x9y0z1a",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1002,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Thanks for the quick response!",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//           contact_inbox: {
//             source_id: "ig_2r3s4t5u6v7w8x9y0z1a",
//           },
//         },
//         sender: {
//           id: 1002,
//           name: "Ben Johnson",
//           available_name: "Ben Johnson",
//           avatar_url: "https://i.pravatar.cc/150?img=2",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=2",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1002,
//         name: "Ben Johnson",
//         email: "ben.johnson@work.net",
//         phone_number: "+44-20-7946-0909",
//         thumbnail: "https://i.pravatar.cc/150?img=2",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-11-15T15:30:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//       },
//       channel: "instagram",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-11-15T15:30:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-07T11:05:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-07T11:05:00.000Z"),
//     last_non_activity_message: {
//       id: 2,
//       content: "Thanks for the quick response!",
//       account_id: 1,
//       inbox_id: 2,
//       conversation_id: 1002,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//       updated_at: "2025-12-07T11:00:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "ig_2r3s4t5u6v7w8x9y0z1a",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1002,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Thanks for the quick response!",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//         contact_inbox: {
//           source_id: "ig_2r3s4t5u6v7w8x9y0z1a",
//         },
//       },
//       sender: {
//         id: 1002,
//         name: "Ben Johnson",
//         available_name: "Ben Johnson",
//         avatar_url: "https://i.pravatar.cc/150?img=2",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=2",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-07T11:00:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1003,
//     account_id: 1,
//     inbox_id: 3,
//     status: "open",
//     timestamp: dateToTimestamp("2025-12-08T09:10:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-08T09:10:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-08T09:10:00.000Z"),
//     unread_count: 1,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_3b4c5d6e7f8g9h0i1j2k",
//     messages: [
//       {
//         id: 3,
//         content: "Is this still available?",
//         account_id: 1,
//         inbox_id: 3,
//         conversation_id: 1003,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//         updated_at: "2025-12-08T09:05:00.000Z",
//         private: false,
//         status: "delivered",
//         source_id: "em_3b4c5d6e7f8g9h0i1j2k",
//         content_type: "incoming_email",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1003,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Is this still available?",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 1,
//           last_activity_at: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//           contact_inbox: {
//             source_id: "em_3b4c5d6e7f8g9h0i1j2k",
//           },
//         },
//         sender: {
//           id: 1003,
//           name: "Chloe Davis",
//           available_name: "Chloe Davis",
//           avatar_url: "https://i.pravatar.cc/150?img=3",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=3",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1003,
//         name: "Chloe Davis",
//         email: "chloe.davis@example.com",
//         phone_number: null,
//         thumbnail: "https://i.pravatar.cc/150?img=3",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-11-20T08:45:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//       },
//       channel: "email",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-11-20T08:45:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-08T09:10:00.000Z"),
//     first_reply_created_at: null,
//     last_non_activity_message: {
//       id: 3,
//       content: "Is this still available?",
//       account_id: 1,
//       inbox_id: 3,
//       conversation_id: 1003,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//       updated_at: "2025-12-08T09:05:00.000Z",
//       private: false,
//       status: "delivered",
//       source_id: "em_3b4c5d6e7f8g9h0i1j2k",
//       content_type: "incoming_email",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1003,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Is this still available?",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 1,
//         last_activity_at: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//         contact_inbox: {
//           source_id: "em_3b4c5d6e7f8g9h0i1j2k",
//         },
//       },
//       sender: {
//         id: 1003,
//         name: "Chloe Davis",
//         available_name: "Chloe Davis",
//         avatar_url: "https://i.pravatar.cc/150?img=3",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=3",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-08T09:05:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1004,
//     account_id: 1,
//     inbox_id: 1,
//     status: "open",
//     timestamp: dateToTimestamp("2025-12-05T12:00:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-05T12:00:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-05T12:00:00.000Z"),
//     unread_count: 1,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_4l5m6n7o8p9q0r1s2t3u",
//     messages: [
//       {
//         id: 4,
//         content: "Can you send me the invoice?",
//         account_id: 1,
//         inbox_id: 1,
//         conversation_id: 1004,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//         updated_at: "2025-12-05T11:55:00.000Z",
//         private: false,
//         status: "delivered",
//         source_id: "wa_4l5m6n7o8p9q0r1s2t3u",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1004,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Can you send me the invoice?",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 1,
//           last_activity_at: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//           contact_inbox: {
//             source_id: "wa_4l5m6n7o8p9q0r1s2t3u",
//           },
//         },
//         sender: {
//           id: 1004,
//           name: "David Rodriguez",
//           available_name: "David Rodriguez",
//           avatar_url: "https://i.pravatar.cc/150?img=4",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=4",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1004,
//         name: "David Rodriguez",
//         email: "david.r@mailprovider.org",
//         phone_number: null,
//         thumbnail: "https://i.pravatar.cc/150?img=4",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-01T12:00:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//       },
//       channel: "whatsapp",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-01T12:00:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-05T12:00:00.000Z"),
//     first_reply_created_at: null,
//     last_non_activity_message: {
//       id: 4,
//       content: "Can you send me the invoice?",
//       account_id: 1,
//       inbox_id: 1,
//       conversation_id: 1004,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//       updated_at: "2025-12-05T11:55:00.000Z",
//       private: false,
//       status: "delivered",
//       source_id: "wa_4l5m6n7o8p9q0r1s2t3u",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1004,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Can you send me the invoice?",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 1,
//         last_activity_at: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//         contact_inbox: {
//           source_id: "wa_4l5m6n7o8p9q0r1s2t3u",
//         },
//       },
//       sender: {
//         id: 1004,
//         name: "David Rodriguez",
//         available_name: "David Rodriguez",
//         avatar_url: "https://i.pravatar.cc/150?img=4",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=4",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-05T11:55:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1005,
//     account_id: 1,
//     inbox_id: 4,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-07T18:45:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-07T18:45:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-07T18:45:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_5v6w7x8y9z0a1b2c3d4e",
//     messages: [
//       {
//         id: 5,
//         content: "Looking forward to it!",
//         account_id: 1,
//         inbox_id: 4,
//         conversation_id: 1005,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//         updated_at: "2025-12-07T18:40:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "sms_5v6w7x8y9z0a1b2c3d4e",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1005,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Looking forward to it!",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//           contact_inbox: {
//             source_id: "sms_5v6w7x8y9z0a1b2c3d4e",
//           },
//         },
//         sender: {
//           id: 1005,
//           name: "Emma Wongs",
//           available_name: "Emma Wongs",
//           avatar_url: "https://i.pravatar.cc/150?img=5",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=5",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1005,
//         name: "Emma Wongs",
//         email: null,
//         phone_number: "+61-400-123-456",
//         thumbnail: "https://i.pravatar.cc/150?img=5",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-02T09:15:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//       },
//       channel: "sms",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-02T09:15:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-07T18:45:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-07T18:45:00.000Z"),
//     last_non_activity_message: {
//       id: 5,
//       content: "Looking forward to it!",
//       account_id: 1,
//       inbox_id: 4,
//       conversation_id: 1005,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//       updated_at: "2025-12-07T18:40:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "sms_5v6w7x8y9z0a1b2c3d4e",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1005,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Looking forward to it!",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//         contact_inbox: {
//           source_id: "sms_5v6w7x8y9z0a1b2c3d4e",
//         },
//       },
//       sender: {
//         id: 1005,
//         name: "Emma Wongs",
//         available_name: "Emma Wongs",
//         avatar_url: "https://i.pravatar.cc/150?img=5",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=5",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-07T18:40:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1006,
//     account_id: 1,
//     inbox_id: 2,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-08T08:05:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-08T08:05:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-08T08:05:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_7p8q9r0s1t2u3v4w5x6y",
//     messages: [
//       {
//         id: 6,
//         content: "Perfect! Thank you so much",
//         account_id: 1,
//         inbox_id: 2,
//         conversation_id: 1006,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//         updated_at: "2025-12-08T08:00:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "ig_7p8q9r0s1t2u3v4w5x6y",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1006,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Perfect! Thank you so much",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//           contact_inbox: {
//             source_id: "ig_7p8q9r0s1t2u3v4w5x6y",
//           },
//         },
//         sender: {
//           id: 1006,
//           name: "Grace Lee",
//           available_name: "Grace Lee",
//           avatar_url: "https://i.pravatar.cc/150?img=7",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=7",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1006,
//         name: "Grace Lee",
//         email: "grace.lee@webmail.co",
//         phone_number: null,
//         thumbnail: "https://i.pravatar.cc/150?img=7",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-04T11:20:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//       },
//       channel: "instagram",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-04T11:20:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-08T08:05:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-08T08:05:00.000Z"),
//     last_non_activity_message: {
//       id: 6,
//       content: "Perfect! Thank you so much",
//       account_id: 1,
//       inbox_id: 2,
//       conversation_id: 1006,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//       updated_at: "2025-12-08T08:00:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "ig_7p8q9r0s1t2u3v4w5x6y",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1006,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Perfect! Thank you so much",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//         contact_inbox: {
//           source_id: "ig_7p8q9r0s1t2u3v4w5x6y",
//         },
//       },
//       sender: {
//         id: 1006,
//         name: "Grace Lee",
//         available_name: "Grace Lee",
//         avatar_url: "https://i.pravatar.cc/150?img=7",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=7",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1007,
//     account_id: 1,
//     inbox_id: 1,
//     status: "open",
//     timestamp: dateToTimestamp("2025-12-07T13:00:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-07T13:00:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-07T13:00:00.000Z"),
//     unread_count: 1,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_8z1a2b3c4d5e6f7g8h9i",
//     messages: [
//       {
//         id: 7,
//         content: "I'll check and get back to you",
//         account_id: 1,
//         inbox_id: 1,
//         conversation_id: 1007,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//         updated_at: "2025-12-07T12:55:00.000Z",
//         private: false,
//         status: "delivered",
//         source_id: "wa_8z1a2b3c4d5e6f7g8h9i",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1007,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "I'll check and get back to you",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 1,
//           last_activity_at: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//           contact_inbox: {
//             source_id: "wa_8z1a2b3c4d5e6f7g8h9i",
//           },
//         },
//         sender: {
//           id: 1007,
//           name: "Henry Wilson",
//           available_name: "Henry Wilson",
//           avatar_url: "https://i.pravatar.cc/150?img=8",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=8",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1007,
//         name: "Henry Wilson",
//         email: null,
//         phone_number: "+33-1-40-00-00-00",
//         thumbnail: "https://i.pravatar.cc/150?img=8",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-05T09:30:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//       },
//       channel: "whatsapp",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-05T09:30:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-07T13:00:00.000Z"),
//     first_reply_created_at: null,
//     last_non_activity_message: {
//       id: 7,
//       content: "I'll check and get back to you",
//       account_id: 1,
//       inbox_id: 1,
//       conversation_id: 1007,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//       updated_at: "2025-12-07T12:55:00.000Z",
//       private: false,
//       status: "delivered",
//       source_id: "wa_8z1a2b3c4d5e6f7g8h9i",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1007,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "I'll check and get back to you",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 1,
//         last_activity_at: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//         contact_inbox: {
//           source_id: "wa_8z1a2b3c4d5e6f7g8h9i",
//         },
//       },
//       sender: {
//         id: 1007,
//         name: "Henry Wilson",
//         available_name: "Henry Wilson",
//         avatar_url: "https://i.pravatar.cc/150?img=8",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=8",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-07T12:55:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1008,
//     account_id: 1,
//     inbox_id: 3,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_9j0k1l2m3n4o5p6q7r8s",
//     messages: [
//       {
//         id: 8,
//         content: "Got it, thanks!",
//         account_id: 1,
//         inbox_id: 3,
//         conversation_id: 1008,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//         updated_at: "2025-12-06T14:40:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "em_9j0k1l2m3n4o5p6q7r8s",
//         content_type: "incoming_email",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1008,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Got it, thanks!",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//           contact_inbox: {
//             source_id: "em_9j0k1l2m3n4o5p6q7r8s",
//           },
//         },
//         sender: {
//           id: 1008,
//           name: "Ivy Chen",
//           available_name: "Ivy Chen",
//           avatar_url: "https://i.pravatar.cc/150?img=9",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=9",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1008,
//         name: "Ivy Chen",
//         email: "ivy.chen@startup.io",
//         phone_number: "+86-10-1234-5678",
//         thumbnail: "https://i.pravatar.cc/150?img=9",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//       },
//       channel: "email",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     last_non_activity_message: {
//       id: 8,
//       content: "Got it, thanks!",
//       account_id: 1,
//       inbox_id: 3,
//       conversation_id: 1008,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//       updated_at: "2025-12-06T14:40:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "em_9j0k1l2m3n4o5p6q7r8s",
//       content_type: "incoming_email",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1008,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Got it, thanks!",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//         contact_inbox: {
//           source_id: "em_9j0k1l2m3n4o5p6q7r8s",
//         },
//       },
//       sender: {
//         id: 1008,
//         name: "Ivy Chen",
//         available_name: "Ivy Chen",
//         avatar_url: "https://i.pravatar.cc/150?img=9",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=9",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-06T14:40:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1009,
//     account_id: 1,
//     inbox_id: 2,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_a1b2c3d4e5f6g7h8i9j0",
//     messages: [
//       {
//         id: 9,
//         content: "Sounds good to me",
//         account_id: 1,
//         inbox_id: 2,
//         conversation_id: 1009,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//         updated_at: "2025-12-08T07:55:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "ig_a1b2c3d4e5f6g7h8i9j0",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1009,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Sounds good to me",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//           contact_inbox: {
//             source_id: "ig_a1b2c3d4e5f6g7h8i9j0",
//           },
//         },
//         sender: {
//           id: 1009,
//           name: "Jack Harris",
//           available_name: "Jack Harris",
//           avatar_url: "https://i.pravatar.cc/150?img=10",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=10",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1009,
//         name: "Jack Harris",
//         email: "jack.h@email.biz",
//         phone_number: null,
//         thumbnail: "https://i.pravatar.cc/150?img=10",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-07T16:00:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//       },
//       channel: "instagram",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-07T16:00:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-08T08:00:00.000Z"),
//     last_non_activity_message: {
//       id: 9,
//       content: "Sounds good to me",
//       account_id: 1,
//       inbox_id: 2,
//       conversation_id: 1009,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//       updated_at: "2025-12-08T07:55:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "ig_a1b2c3d4e5f6g7h8i9j0",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1009,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Sounds good to me",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//         contact_inbox: {
//           source_id: "ig_a1b2c3d4e5f6g7h8i9j0",
//         },
//       },
//       sender: {
//         id: 1009,
//         name: "Jack Harris",
//         available_name: "Jack Harris",
//         avatar_url: "https://i.pravatar.cc/150?img=10",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=10",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-08T07:55:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1010,
//     account_id: 1,
//     inbox_id: 4,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_b1c2d3e4f5g6h7i8j9k0",
//     messages: [
//       {
//         id: 10,
//         content: "Will do, thanks!",
//         account_id: 1,
//         inbox_id: 4,
//         conversation_id: 1010,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//         updated_at: "2025-12-08T10:00:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "sms_b1c2d3e4f5g6h7i8j9k0",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1010,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Will do, thanks!",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//           contact_inbox: {
//             source_id: "sms_b1c2d3e4f5g6h7i8j9k0",
//           },
//         },
//         sender: {
//           id: 1010,
//           name: "Kelly White",
//           available_name: "Kelly White",
//           avatar_url: "https://i.pravatar.cc/150?img=11",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=11",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1010,
//         name: "Kelly White",
//         email: null,
//         phone_number: "+1-555-0103",
//         thumbnail: "https://i.pravatar.cc/150?img=11",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//       },
//       channel: "sms",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     last_non_activity_message: {
//       id: 10,
//       content: "Will do, thanks!",
//       account_id: 1,
//       inbox_id: 4,
//       conversation_id: 1010,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//       updated_at: "2025-12-08T10:00:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "sms_b1c2d3e4f5g6h7i8j9k0",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1010,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Will do, thanks!",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//         contact_inbox: {
//           source_id: "sms_b1c2d3e4f5g6h7i8j9k0",
//         },
//       },
//       sender: {
//         id: 1010,
//         name: "Kelly White",
//         available_name: "Kelly White",
//         avatar_url: "https://i.pravatar.cc/150?img=11",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=11",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-08T10:00:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1011,
//     account_id: 1,
//     inbox_id: 1,
//     status: "open",
//     timestamp: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     unread_count: 1,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_c1d2e3f4g5h6i7j8k9l0",
//     messages: [
//       {
//         id: 11,
//         content: "When can I expect delivery?",
//         account_id: 1,
//         inbox_id: 1,
//         conversation_id: 1011,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//         updated_at: "2025-12-09T07:30:00.000Z",
//         private: false,
//         status: "delivered",
//         source_id: "wa_c1d2e3f4g5h6i7j8k9l0",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1011,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "When can I expect delivery?",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 1,
//           last_activity_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//           contact_inbox: {
//             source_id: "wa_c1d2e3f4g5h6i7j8k9l0",
//           },
//         },
//         sender: {
//           id: 1011,
//           name: "Leo Martinez",
//           available_name: "Leo Martinez",
//           avatar_url: "https://i.pravatar.cc/150?img=12",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=12",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1011,
//         name: "Leo Martinez",
//         email: "leo.m@anothermail.com",
//         phone_number: null,
//         thumbnail: "https://i.pravatar.cc/150?img=12",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//       },
//       channel: "whatsapp",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     first_reply_created_at: null,
//     last_non_activity_message: {
//       id: 11,
//       content: "When can I expect delivery?",
//       account_id: 1,
//       inbox_id: 1,
//       conversation_id: 1011,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//       updated_at: "2025-12-09T07:30:00.000Z",
//       private: false,
//       status: "delivered",
//       source_id: "wa_c1d2e3f4g5h6i7j8k9l0",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1011,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "When can I expect delivery?",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 1,
//         last_activity_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//         contact_inbox: {
//           source_id: "wa_c1d2e3f4g5h6i7j8k9l0",
//         },
//       },
//       sender: {
//         id: 1011,
//         name: "Leo Martinez",
//         available_name: "Leo Martinez",
//         avatar_url: "https://i.pravatar.cc/150?img=12",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=12",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-09T07:30:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1012,
//     account_id: 1,
//     inbox_id: 3,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_d1e2f3g4h5i6j7k8l9m0",
//     messages: [
//       {
//         id: 12,
//         content: "Great service, highly recommended!",
//         account_id: 1,
//         inbox_id: 3,
//         conversation_id: 1012,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//         updated_at: "2025-12-10T12:15:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "em_d1e2f3g4h5i6j7k8l9m0",
//         content_type: "incoming_email",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1012,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Great service, highly recommended!",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//           contact_inbox: {
//             source_id: "em_d1e2f3g4h5i6j7k8l9m0",
//           },
//         },
//         sender: {
//           id: 1012,
//           name: "Mia Garcia",
//           available_name: "Mia Garcia",
//           avatar_url: "https://i.pravatar.cc/150?img=13",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=13",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1012,
//         name: "Mia Garcia",
//         email: "mia.garcia@example.com",
//         phone_number: null,
//         thumbnail: "https://i.pravatar.cc/150?img=13",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//       },
//       channel: "email",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     last_non_activity_message: {
//       id: 12,
//       content: "Great service, highly recommended!",
//       account_id: 1,
//       inbox_id: 3,
//       conversation_id: 1012,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//       updated_at: "2025-12-10T12:15:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "em_d1e2f3g4h5i6j7k8l9m0",
//       content_type: "incoming_email",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1012,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Great service, highly recommended!",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//         contact_inbox: {
//           source_id: "em_d1e2f3g4h5i6j7k8l9m0",
//         },
//       },
//       sender: {
//         id: 1012,
//         name: "Mia Garcia",
//         available_name: "Mia Garcia",
//         avatar_url: "https://i.pravatar.cc/150?img=13",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=13",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-10T12:15:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1013,
//     account_id: 1,
//     inbox_id: 2,
//     status: "open",
//     timestamp: dateToTimestamp("2025-12-12T09:00:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-12T09:00:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-12T09:00:00.000Z"),
//     unread_count: 1,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_e1f2g3h4i5j6k7l8m9n0",
//     messages: [
//       {
//         id: 13,
//         content: "I need more information please",
//         account_id: 1,
//         inbox_id: 2,
//         conversation_id: 1013,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//         updated_at: "2025-12-12T08:55:00.000Z",
//         private: false,
//         status: "delivered",
//         source_id: "ig_e1f2g3h4i5j6k7l8m9n0",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1013,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "I need more information please",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 1,
//           last_activity_at: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//           contact_inbox: {
//             source_id: "ig_e1f2g3h4i5j6k7l8m9n0",
//           },
//         },
//         sender: {
//           id: 1013,
//           name: "Noah Brown",
//           available_name: "Noah Brown",
//           avatar_url: "https://i.pravatar.cc/150?img=14",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=14",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1013,
//         name: "Noah Brown",
//         email: "noah.b@provider.net",
//         phone_number: "+49-30-1111-2222",
//         thumbnail: "https://i.pravatar.cc/150?img=14",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-11T17:00:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//       },
//       channel: "instagram",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-11T17:00:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-12T09:00:00.000Z"),
//     first_reply_created_at: null,
//     last_non_activity_message: {
//       id: 13,
//       content: "I need more information please",
//       account_id: 1,
//       inbox_id: 2,
//       conversation_id: 1013,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//       updated_at: "2025-12-12T08:55:00.000Z",
//       private: false,
//       status: "delivered",
//       source_id: "ig_e1f2g3h4i5j6k7l8m9n0",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1013,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "I need more information please",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 1,
//         last_activity_at: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//         contact_inbox: {
//           source_id: "ig_e1f2g3h4i5j6k7l8m9n0",
//         },
//       },
//       sender: {
//         id: 1013,
//         name: "Noah Brown",
//         available_name: "Noah Brown",
//         avatar_url: "https://i.pravatar.cc/150?img=14",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=14",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-12T08:55:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1014,
//     account_id: 1,
//     inbox_id: 4,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-12T10:00:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-12T10:00:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-12T10:00:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {},
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_f1g2h3i4j5k6l7m8n9o0",
//     messages: [
//       {
//         id: 14,
//         content: "That works for me!",
//         account_id: 1,
//         inbox_id: 4,
//         conversation_id: 1014,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//         updated_at: "2025-12-12T09:55:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "sms_f1g2h3i4j5k6l7m8n9o0",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1014,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "That works for me!",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//           contact_inbox: {
//             source_id: "sms_f1g2h3i4j5k6l7m8n9o0",
//           },
//         },
//         sender: {
//           id: 1014,
//           name: "Olivia Moore",
//           available_name: "Olivia Moore",
//           avatar_url: "https://i.pravatar.cc/150?img=15",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=15",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1014,
//         name: "Olivia Moore",
//         email: "olivia.moore@mail.me",
//         phone_number: "+1-555-0104",
//         thumbnail: "https://i.pravatar.cc/150?img=15",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-12T08:30:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//       },
//       channel: "sms",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-12T08:30:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-12T10:00:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-12T10:00:00.000Z"),
//     last_non_activity_message: {
//       id: 14,
//       content: "That works for me!",
//       account_id: 1,
//       inbox_id: 4,
//       conversation_id: 1014,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//       updated_at: "2025-12-12T09:55:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "sms_f1g2h3i4j5k6l7m8n9o0",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1014,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "That works for me!",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//         contact_inbox: {
//           source_id: "sms_f1g2h3i4j5k6l7m8n9o0",
//         },
//       },
//       sender: {
//         id: 1014,
//         name: "Olivia Moore",
//         available_name: "Olivia Moore",
//         avatar_url: "https://i.pravatar.cc/150?img=15",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=15",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-12T09:55:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1015,
//     account_id: 1,
//     inbox_id: 5,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-13T14:20:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-13T14:20:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-13T14:20:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {
//       chat_id: 1015,
//       business_connection_id: null,
//     },
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_t1e2l3e4g5r6a7m8u9s0",
//     messages: [
//       {
//         id: 15,
//         content: "Отлично! Спасибо",
//         account_id: 1,
//         inbox_id: 5,
//         conversation_id: 1015,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//         updated_at: "2025-12-13T14:18:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "tg_t1e2l3e4g5r6a7m8u9s0",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1015,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Отлично! Спасибо",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//           contact_inbox: {
//             source_id: "tg_t1e2l3e4g5r6a7m8u9s0",
//           },
//         },
//         sender: {
//           id: 1015,
//           name: "Alex Petrov",
//           available_name: "Alex Petrov",
//           avatar_url: "https://i.pravatar.cc/150?img=16",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=16",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1015,
//         name: "Alex Petrov",
//         email: "alex.petrov@telegram.ru",
//         phone_number: "+7-495-123-4567",
//         thumbnail: "https://i.pravatar.cc/150?img=16",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-13T14:15:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//       },
//       channel: "telegram",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-13T14:15:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-13T14:20:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-13T14:20:00.000Z"),
//     last_non_activity_message: {
//       id: 15,
//       content: "Отлично! Спасибо",
//       account_id: 1,
//       inbox_id: 5,
//       conversation_id: 1015,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//       updated_at: "2025-12-13T14:18:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "tg_t1e2l3e4g5r6a7m8u9s0",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1015,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Отлично! Спасибо",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//         contact_inbox: {
//           source_id: "tg_t1e2l3e4g5r6a7m8u9s0",
//         },
//       },
//       sender: {
//         id: 1015,
//         name: "Alex Petrov",
//         available_name: "Alex Petrov",
//         avatar_url: "https://i.pravatar.cc/150?img=16",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=16",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-13T14:18:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1016,
//     account_id: 1,
//     inbox_id: 5,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-13T15:30:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-13T15:30:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-13T15:30:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {
//       chat_id: 1016,
//       business_connection_id: null,
//     },
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_t2e3l4e5g6r7a8m9u0s1",
//     messages: [
//       {
//         id: 16,
//         content: "谢谢！很有帮助",
//         account_id: 1,
//         inbox_id: 5,
//         conversation_id: 1016,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//         updated_at: "2025-12-13T15:25:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "tg_t2e3l4e5g6r7a8m9u0s1",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1016,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "谢谢！很有帮助",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//           contact_inbox: {
//             source_id: "tg_t2e3l4e5g6r7a8m9u0s1",
//           },
//         },
//         sender: {
//           id: 1016,
//           name: "Sophia Chen",
//           available_name: "Sophia Chen",
//           avatar_url: "https://i.pravatar.cc/150?img=17",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=17",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1016,
//         name: "Sophia Chen",
//         email: "sophia.chen@example.com",
//         phone_number: "+86-138-0013-8000",
//         thumbnail: "https://i.pravatar.cc/150?img=17",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-13T15:00:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//       },
//       channel: "telegram",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-13T15:00:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-13T15:30:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-13T15:30:00.000Z"),
//     last_non_activity_message: {
//       id: 16,
//       content: "谢谢！很有帮助",
//       account_id: 1,
//       inbox_id: 5,
//       conversation_id: 1016,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//       updated_at: "2025-12-13T15:25:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "tg_t2e3l4e5g6r7a8m9u0s1",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1016,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "谢谢！很有帮助",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//         contact_inbox: {
//           source_id: "tg_t2e3l4e5g6r7a8m9u0s1",
//         },
//       },
//       sender: {
//         id: 1016,
//         name: "Sophia Chen",
//         available_name: "Sophia Chen",
//         avatar_url: "https://i.pravatar.cc/150?img=17",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=17",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-13T15:25:00.000Z"),
//     sla_policy_id: null,
//   },
//   {
//     id: 1017,
//     account_id: 1,
//     inbox_id: 5,
//     status: "resolved",
//     timestamp: dateToTimestamp("2025-12-13T16:45:00.000Z"),
//     contact_last_seen_at: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//     agent_last_seen_at: dateToTimestamp("2025-12-13T16:45:00.000Z"),
//     assignee_last_seen_at: dateToTimestamp("2025-12-13T16:45:00.000Z"),
//     unread_count: 0,
//     additional_attributes: {
//       chat_id: 1017,
//       business_connection_id: null,
//     },
//     custom_attributes: {},
//     can_reply: true,
//     uuid: "cl_t3e4l5e6g7r8a9m0u1s2",
//     messages: [
//       {
//         id: 17,
//         content: "Perfetto! Grazie mille",
//         account_id: 1,
//         inbox_id: 5,
//         conversation_id: 1017,
//         message_type: 0,
//         created_at: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//         updated_at: "2025-12-13T16:43:00.000Z",
//         private: false,
//         status: "read",
//         source_id: "tg_t3e4l5e6g7r8a9m0u1s2",
//         content_type: "text",
//         content_attributes: {},
//         sender_type: "Contact",
//         sender_id: 1017,
//         external_source_ids: {},
//         additional_attributes: {},
//         processed_message_content: "Perfetto! Grazie mille",
//         sentiment: {},
//         conversation: {
//           assignee_id: null,
//           unread_count: 0,
//           last_activity_at: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//           contact_inbox: {
//             source_id: "tg_t3e4l5e6g7r8a9m0u1s2",
//           },
//         },
//         sender: {
//           id: 1017,
//           name: "Marco Rossi",
//           available_name: "Marco Rossi",
//           avatar_url: "https://i.pravatar.cc/150?img=18",
//           type: "Contact",
//           availability_status: "online",
//           thumbnail: "https://i.pravatar.cc/150?img=18",
//         },
//       },
//     ],
//     meta: {
//       sender: {
//         id: 1017,
//         name: "Marco Rossi",
//         email: "marco.rossi@example.it",
//         phone_number: "+39-02-1234-5678",
//         thumbnail: "https://i.pravatar.cc/150?img=18",
//         additional_attributes: {},
//         custom_attributes: {},
//         identifier: null,
//         blocked: false,
//         availability_status: "online",
//         created_at: dateToTimestamp("2025-12-13T16:40:00.000Z"),
//         last_activity_at: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//       },
//       channel: "telegram",
//       hmac_verified: true,
//     },
//     labels: [],
//     muted: false,
//     snoozed_until: null,
//     created_at: dateToTimestamp("2025-12-13T16:40:00.000Z"),
//     updated_at: dateToTimestamp("2025-12-13T16:45:00.000Z"),
//     first_reply_created_at: dateToTimestamp("2025-12-13T16:45:00.000Z"),
//     last_non_activity_message: {
//       id: 17,
//       content: "Perfetto! Grazie mille",
//       account_id: 1,
//       inbox_id: 5,
//       conversation_id: 1017,
//       message_type: 0,
//       created_at: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//       updated_at: "2025-12-13T16:43:00.000Z",
//       private: false,
//       status: "read",
//       source_id: "tg_t3e4l5e6g7r8a9m0u1s2",
//       content_type: "text",
//       content_attributes: {},
//       sender_type: "Contact",
//       sender_id: 1017,
//       external_source_ids: {},
//       additional_attributes: {},
//       processed_message_content: "Perfetto! Grazie mille",
//       sentiment: {},
//       conversation: {
//         assignee_id: null,
//         unread_count: 0,
//         last_activity_at: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//         contact_inbox: {
//           source_id: "tg_t3e4l5e6g7r8a9m0u1s2",
//         },
//       },
//       sender: {
//         id: 1017,
//         name: "Marco Rossi",
//         available_name: "Marco Rossi",
//         avatar_url: "https://i.pravatar.cc/150?img=18",
//         type: "Contact",
//         availability_status: "online",
//         thumbnail: "https://i.pravatar.cc/150?img=18",
//       },
//     },
//     last_activity_at: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//     priority: null,
//     waiting_since: dateToTimestamp("2025-12-13T16:43:00.000Z"),
//     sla_policy_id: null,
//   },
// ];
